name: Release
on:
  push:
    branches:
      - main

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.4'
      - name: Go Version
        run: go version
      - uses: wangyoucao577/go-release-action@v1.11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz"
          binary_name: "gpm"
          extra_files: LICENSE README.md
